version: '3.8'
services:
  mysql-pismo:
    image: mysql:latest
    container_name: mysql-pismo
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=pismo
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - ./.sql-scripts/:/docker-entrypoint-initdb.d/
  pismo: &pismo
    container_name: pismo
    build:
      context: .
      dockerfile: cmd/pismo/Dockerfile
    #volumes:
    #  - /home/diego.almeida/projects/go/src/pismo-back-teste:/go/src/pismo-back-teste
    ports:
      - '8080:80'
    depends_on:
      - mysql-pismo
